FROM oven/bun:1
WORKDIR /app
COPY package.json bun.lockb* ./
COPY apps/web/package.json ./apps/web/
COPY packages ./packages/
RUN bun install
COPY . .
WORKDIR /app/apps/web
EXPOSE 4173
CMD ["bun", "run", "dev"]
