// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: dolphin.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IncomingMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PhoneId       string                 `protobuf:"bytes,1,opt,name=phone_id,json=phoneId,proto3" json:"phone_id,omitempty"`       // "5511999999999"
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`                            // The raw text from WA
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                 // Unix timestamp
	MessageId     string                 `protobuf:"bytes,4,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"` // WA Message ID
	TenantId      string                 `protobuf:"bytes,5,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`    // Added for isolation
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncomingMessage) Reset() {
	*x = IncomingMessage{}
	mi := &file_dolphin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncomingMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncomingMessage) ProtoMessage() {}

func (x *IncomingMessage) ProtoReflect() protoreflect.Message {
	mi := &file_dolphin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncomingMessage.ProtoReflect.Descriptor instead.
func (*IncomingMessage) Descriptor() ([]byte, []int) {
	return file_dolphin_proto_rawDescGZIP(), []int{0}
}

func (x *IncomingMessage) GetPhoneId() string {
	if x != nil {
		return x.PhoneId
	}
	return ""
}

func (x *IncomingMessage) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *IncomingMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *IncomingMessage) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *IncomingMessage) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type ProcessStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Received      bool                   `protobuf:"varint,1,opt,name=received,proto3" json:"received,omitempty"`             // Ack back to Go
	TraceId       string                 `protobuf:"bytes,2,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"` // Tracing ID for logs
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessStatus) Reset() {
	*x = ProcessStatus{}
	mi := &file_dolphin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessStatus) ProtoMessage() {}

func (x *ProcessStatus) ProtoReflect() protoreflect.Message {
	mi := &file_dolphin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessStatus.ProtoReflect.Descriptor instead.
func (*ProcessStatus) Descriptor() ([]byte, []int) {
	return file_dolphin_proto_rawDescGZIP(), []int{1}
}

func (x *ProcessStatus) GetReceived() bool {
	if x != nil {
		return x.Received
	}
	return false
}

func (x *ProcessStatus) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

type OutboundMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PhoneId       string                 `protobuf:"bytes,1,opt,name=phone_id,json=phoneId,proto3" json:"phone_id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	TenantId      string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"` // Added for isolation
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutboundMessage) Reset() {
	*x = OutboundMessage{}
	mi := &file_dolphin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutboundMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutboundMessage) ProtoMessage() {}

func (x *OutboundMessage) ProtoReflect() protoreflect.Message {
	mi := &file_dolphin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutboundMessage.ProtoReflect.Descriptor instead.
func (*OutboundMessage) Descriptor() ([]byte, []int) {
	return file_dolphin_proto_rawDescGZIP(), []int{2}
}

func (x *OutboundMessage) GetPhoneId() string {
	if x != nil {
		return x.PhoneId
	}
	return ""
}

func (x *OutboundMessage) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *OutboundMessage) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type DispatchStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DispatchStatus) Reset() {
	*x = DispatchStatus{}
	mi := &file_dolphin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchStatus) ProtoMessage() {}

func (x *DispatchStatus) ProtoReflect() protoreflect.Message {
	mi := &file_dolphin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchStatus.ProtoReflect.Descriptor instead.
func (*DispatchStatus) Descriptor() ([]byte, []int) {
	return file_dolphin_proto_rawDescGZIP(), []int{3}
}

func (x *DispatchStatus) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DispatchStatus) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_dolphin_proto protoreflect.FileDescriptor

const file_dolphin_proto_rawDesc = "" +
	"\n" +
	"\rdolphin.proto\x12\adolphin\"\x9a\x01\n" +
	"\x0fIncomingMessage\x12\x19\n" +
	"\bphone_id\x18\x01 \x01(\tR\aphoneId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12\x1d\n" +
	"\n" +
	"message_id\x18\x04 \x01(\tR\tmessageId\x12\x1b\n" +
	"\ttenant_id\x18\x05 \x01(\tR\btenantId\"F\n" +
	"\rProcessStatus\x12\x1a\n" +
	"\breceived\x18\x01 \x01(\bR\breceived\x12\x19\n" +
	"\btrace_id\x18\x02 \x01(\tR\atraceId\"]\n" +
	"\x0fOutboundMessage\x12\x19\n" +
	"\bphone_id\x18\x01 \x01(\tR\aphoneId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\"O\n" +
	"\x0eDispatchStatus\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage2U\n" +
	"\x0fCognitiveEngine\x12B\n" +
	"\x0eProcessMessage\x12\x18.dolphin.IncomingMessage\x1a\x16.dolphin.ProcessStatus2R\n" +
	"\x0eGatewayControl\x12@\n" +
	"\vSendMessage\x12\x18.dolphin.OutboundMessage\x1a\x17.dolphin.DispatchStatusB\x06Z\x04./pbb\x06proto3"

var (
	file_dolphin_proto_rawDescOnce sync.Once
	file_dolphin_proto_rawDescData []byte
)

func file_dolphin_proto_rawDescGZIP() []byte {
	file_dolphin_proto_rawDescOnce.Do(func() {
		file_dolphin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dolphin_proto_rawDesc), len(file_dolphin_proto_rawDesc)))
	})
	return file_dolphin_proto_rawDescData
}

var file_dolphin_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_dolphin_proto_goTypes = []any{
	(*IncomingMessage)(nil), // 0: dolphin.IncomingMessage
	(*ProcessStatus)(nil),   // 1: dolphin.ProcessStatus
	(*OutboundMessage)(nil), // 2: dolphin.OutboundMessage
	(*DispatchStatus)(nil),  // 3: dolphin.DispatchStatus
}
var file_dolphin_proto_depIdxs = []int32{
	0, // 0: dolphin.CognitiveEngine.ProcessMessage:input_type -> dolphin.IncomingMessage
	2, // 1: dolphin.GatewayControl.SendMessage:input_type -> dolphin.OutboundMessage
	1, // 2: dolphin.CognitiveEngine.ProcessMessage:output_type -> dolphin.ProcessStatus
	3, // 3: dolphin.GatewayControl.SendMessage:output_type -> dolphin.DispatchStatus
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_dolphin_proto_init() }
func file_dolphin_proto_init() {
	if File_dolphin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dolphin_proto_rawDesc), len(file_dolphin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_dolphin_proto_goTypes,
		DependencyIndexes: file_dolphin_proto_depIdxs,
		MessageInfos:      file_dolphin_proto_msgTypes,
	}.Build()
	File_dolphin_proto = out.File
	file_dolphin_proto_goTypes = nil
	file_dolphin_proto_depIdxs = nil
}
