// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: dolphin.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CognitiveEngine_ProcessMessage_FullMethodName = "/dolphin.CognitiveEngine/ProcessMessage"
)

// CognitiveEngineClient is the client API for CognitiveEngine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CognitiveEngineClient interface {
	// Sends a WhatsApp message from Gateway (Go) -> Motor (Rust)
	ProcessMessage(ctx context.Context, in *IncomingMessage, opts ...grpc.CallOption) (*ProcessStatus, error)
}

type cognitiveEngineClient struct {
	cc grpc.ClientConnInterface
}

func NewCognitiveEngineClient(cc grpc.ClientConnInterface) CognitiveEngineClient {
	return &cognitiveEngineClient{cc}
}

func (c *cognitiveEngineClient) ProcessMessage(ctx context.Context, in *IncomingMessage, opts ...grpc.CallOption) (*ProcessStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProcessStatus)
	err := c.cc.Invoke(ctx, CognitiveEngine_ProcessMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CognitiveEngineServer is the server API for CognitiveEngine service.
// All implementations must embed UnimplementedCognitiveEngineServer
// for forward compatibility.
type CognitiveEngineServer interface {
	// Sends a WhatsApp message from Gateway (Go) -> Motor (Rust)
	ProcessMessage(context.Context, *IncomingMessage) (*ProcessStatus, error)
	mustEmbedUnimplementedCognitiveEngineServer()
}

// UnimplementedCognitiveEngineServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCognitiveEngineServer struct{}

func (UnimplementedCognitiveEngineServer) ProcessMessage(context.Context, *IncomingMessage) (*ProcessStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method ProcessMessage not implemented")
}
func (UnimplementedCognitiveEngineServer) mustEmbedUnimplementedCognitiveEngineServer() {}
func (UnimplementedCognitiveEngineServer) testEmbeddedByValue()                         {}

// UnsafeCognitiveEngineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CognitiveEngineServer will
// result in compilation errors.
type UnsafeCognitiveEngineServer interface {
	mustEmbedUnimplementedCognitiveEngineServer()
}

func RegisterCognitiveEngineServer(s grpc.ServiceRegistrar, srv CognitiveEngineServer) {
	// If the following call panics, it indicates UnimplementedCognitiveEngineServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CognitiveEngine_ServiceDesc, srv)
}

func _CognitiveEngine_ProcessMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IncomingMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CognitiveEngineServer).ProcessMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CognitiveEngine_ProcessMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CognitiveEngineServer).ProcessMessage(ctx, req.(*IncomingMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// CognitiveEngine_ServiceDesc is the grpc.ServiceDesc for CognitiveEngine service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CognitiveEngine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dolphin.CognitiveEngine",
	HandlerType: (*CognitiveEngineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessMessage",
			Handler:    _CognitiveEngine_ProcessMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dolphin.proto",
}

const (
	GatewayControl_SendMessage_FullMethodName = "/dolphin.GatewayControl/SendMessage"
)

// GatewayControlClient is the client API for GatewayControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GatewayControlClient interface {
	// Command from Motor (Rust) -> Gateway (Go) to dispatch an outbound message
	SendMessage(ctx context.Context, in *OutboundMessage, opts ...grpc.CallOption) (*DispatchStatus, error)
}

type gatewayControlClient struct {
	cc grpc.ClientConnInterface
}

func NewGatewayControlClient(cc grpc.ClientConnInterface) GatewayControlClient {
	return &gatewayControlClient{cc}
}

func (c *gatewayControlClient) SendMessage(ctx context.Context, in *OutboundMessage, opts ...grpc.CallOption) (*DispatchStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DispatchStatus)
	err := c.cc.Invoke(ctx, GatewayControl_SendMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GatewayControlServer is the server API for GatewayControl service.
// All implementations must embed UnimplementedGatewayControlServer
// for forward compatibility.
type GatewayControlServer interface {
	// Command from Motor (Rust) -> Gateway (Go) to dispatch an outbound message
	SendMessage(context.Context, *OutboundMessage) (*DispatchStatus, error)
	mustEmbedUnimplementedGatewayControlServer()
}

// UnimplementedGatewayControlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGatewayControlServer struct{}

func (UnimplementedGatewayControlServer) SendMessage(context.Context, *OutboundMessage) (*DispatchStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedGatewayControlServer) mustEmbedUnimplementedGatewayControlServer() {}
func (UnimplementedGatewayControlServer) testEmbeddedByValue()                        {}

// UnsafeGatewayControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GatewayControlServer will
// result in compilation errors.
type UnsafeGatewayControlServer interface {
	mustEmbedUnimplementedGatewayControlServer()
}

func RegisterGatewayControlServer(s grpc.ServiceRegistrar, srv GatewayControlServer) {
	// If the following call panics, it indicates UnimplementedGatewayControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GatewayControl_ServiceDesc, srv)
}

func _GatewayControl_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OutboundMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayControlServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayControl_SendMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayControlServer).SendMessage(ctx, req.(*OutboundMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// GatewayControl_ServiceDesc is the grpc.ServiceDesc for GatewayControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GatewayControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dolphin.GatewayControl",
	HandlerType: (*GatewayControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMessage",
			Handler:    _GatewayControl_SendMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dolphin.proto",
}
