FROM oven/bun:1
WORKDIR /app
COPY package.json bun.lockb* ./
COPY apps/web-rep/package.json ./apps/web-rep/
COPY packages ./packages/
RUN bun install
COPY . .
WORKDIR /app/apps/web-rep
EXPOSE 4174
CMD ["bun", "run", "dev"]
