FROM oven/bun:1
WORKDIR /app
COPY package.json bun.lockb* ./
COPY apps/workers/package.json ./apps/workers/
COPY packages ./packages/
RUN bun install
COPY . .
WORKDIR /app/apps/workers
CMD ["bun", "run", "dev"]
