FROM oven/bun:1
WORKDIR /app
COPY package.json bun.lockb* ./
COPY apps/api/package.json ./apps/api/
COPY packages ./packages/
RUN bun install
COPY . .
WORKDIR /app/apps/api
EXPOSE 4000
CMD ["bun", "run", "dev"]
